# Generated by Django 5.2.4 on 2025-07-12 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('home', 'Home & Garden'), ('sports', 'Sports & Recreation'), ('books', 'Books & Media'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('tools', 'Tools & Equipment'), ('jewelry', 'Jewelry & Accessories'), ('other', 'Other')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New - Never used'), ('like-new', 'Like New - Barely used'), ('good', 'Good - Some wear'), ('fair', 'Fair - Noticeable wear'), ('poor', 'Poor - Significant wear')], max_length=20)),
                ('images', models.ImageField(upload_to='items/')),
                ('status', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
