# Generated by Django 5.2.4 on 2025-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_item_images_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
