# Generated by Django 5.2.4 on 2025-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('Track', 'Track'), ('Dress', 'Dress')], max_length=50),
        ),
    ]
